# Generated by Django 2.0 on 2017-12-17 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alexmateva', '0002_auto_20171217_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alexmateva.Event')),
            ],
        ),
    ]
