# Generated by Django 2.0 on 2017-12-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20171217_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='name',
            field=models.CharField(default='snow', max_length=255),
            preserve_default=False,
        ),
    ]
