# Generated by Django 2.0 on 2017-12-16 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 12, 16, 16, 4, 50, 183193, tzinfo=utc))),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(upload_to=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(editable=False, on_delete='CASECADE', to='alexmateva.User'),
        ),
    ]
