# Generated by Django 2.0 on 2017-12-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexmateva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
