# Generated by Django 2.0 on 2017-12-16 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alexmateva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 16, 16, 9, 32, 547690, tzinfo=utc)),
        ),
    ]
