# Generated by Django 2.0 on 2017-12-16 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alexmateva', '0002_auto_20171216_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 16, 16, 9, 44, 988479, tzinfo=utc)),
        ),
    ]
