# Generated by Django 2.0 on 2017-12-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alexmateva', '0002_auto_20171216_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
    ]
