# Generated by Django 2.0 on 2017-12-16 18:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alexmateva', '0003_auto_20171216_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 16, 18, 3, 49, 609765, tzinfo=utc)),
        ),
    ]
